### ISSUE TITLE
Move to the end of the location bar

### ISSUE THREAD

**Issue by ReporterX** [hensm/reloader#11]
Once installed it is on the left hand side of bookmark icon now. 

Is it possible to have to at the end of the location, after bookmark icon (like the image below)? Thank you.

![move to the end](https://addons.cdn.mozilla.net/user-media/previews/full/189/189484.png)

**Comment by hensm** [comment]
You can move it with CSS, but it can't be done from the extension:

````css
#pageAction-urlbar-reloader_matt_tf {
    -moz-box-ordinal-group: 2 !important;
}
````
